name = "KidneyAllocation"
uuid = "3a2243a4-d160-449f-81bc-9a6af01d47fb"
authors = ["Jonathan Jalbert <39426670+jojal5@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
DecisionTree = "0.12.4"
Distributions = "0.25.123"
GLM = "1.9.3"
JLD2 = "0.6.3"
Random = "1.11.0"
StatsModels = "0.7.8"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
